### ISSUE TITLE
BioaRchive Roadmap

### ISSUE THREAD

**Issue by bgruening** [bioarchive/aRchive_source_code#29]
- relation between bioA and CPC
  - PR to check content, bioA will query CPC and download data
- don't allow people to upload data
- Galaxy and [gsl](https://github.com/erasche/community-package-cache/blob/master/bin/gsl.py) are providing a unique ID retrieving the checksum from CPC and the tarball from bioA
- CPC acts as an control instance (PR) to check packages and prevent abusing the file hosting
- bioA webservice to generate r-tool dependencies?
- moving to galaxyproject.org

@erasche  @nitesh1989 do you have time to discuss the way forward here on Thursday?

**Comment by hexylena** [comment]
yep, will have time.

**Comment by nturaga** [comment]
Sounds good!

**Comment by hexylena** [comment]
Okay, i'd like to launch a roadmap from here. We need to improve the underlying infrastructure of bioaRchive because right now the metadata stuff is lacking and that's hurting us.

## TODO
- [x] add a v2 script + database
  - [ ] run through every svn rev, capture a list of all packages and versions available at that time and their dependencies.
  - [ ] Expose this database somehow (even if just as a .sqlite file, heck websqlite means we could use it on the client-side)
  - What we're currently doing is...unpleasant here. We capture some but not all of the metadata and we step back and forth through history wildly. It takes forever to calculate the changes, and we have to re-do the entire process. We could clean up the code significantly by rewriting as an incremental process.
- [ ] script to export database contents as a cpc-compatible urls.tsv
- [ ] module to upload artefacts to the galaxy conda repo.

**Comment by hexylena** [comment]
If anyone knows how to do an `svn diff` without connecting to the network, I'd be really appreciative... every set of CLI options I've tried all contact the upstream server just to calculate a diff between two revisions in the local copy's history... :crying_cat_face:

**Comment by hexylena** [comment]
https://github.com/Bioconductor-mirror

what the actual heck. They individually mirrored repository histories for every sub repo into a separate git repo? O_o
